title: Manny Cassar
description: Manny's Portfolio Blog
permalink: ':title/'
baseurl: ""
url: "https://portfolio.mannytech.net" 
site-twitter:

# Author Settings
author: Manny Cassar
author-img: Manny.jpg
about-author: Curious and driven Software Engineer fueled by challenging problems on innovative projects in AI and software architecture of embedded systems.
social-github: mcassar4
social-linkedin: mannycassar
social-email: m.cassar@queensu.ca

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
